// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ5O9ih77bKjxjNJpucSJwepBe84AsuCw',
    appId: '1:706382510190:web:29435a3369b39dfe4d8e7f',
    messagingSenderId: '706382510190',
    projectId: 'flutternotify1',
    authDomain: 'flutternotify1.firebaseapp.com',
    databaseURL: 'https://flutternotify1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutternotify1.appspot.com',
    measurementId: 'G-K4VHKS2K70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zXdEqO37BKsNteXCDk9U3lG7Ar3h_Vk',
    appId: '1:706382510190:android:de66e1fdb72629a44d8e7f',
    messagingSenderId: '706382510190',
    projectId: 'flutternotify1',
    databaseURL: 'https://flutternotify1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutternotify1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALX5pppdnSPrGOJreGRkF1SzvWbY6AdRI',
    appId: '1:706382510190:ios:b528460808d4b8a44d8e7f',
    messagingSenderId: '706382510190',
    projectId: 'flutternotify1',
    databaseURL: 'https://flutternotify1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutternotify1.appspot.com',
    iosBundleId: 'com.example.firebaselogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALX5pppdnSPrGOJreGRkF1SzvWbY6AdRI',
    appId: '1:706382510190:ios:e1e9fc4c24b3f37e4d8e7f',
    messagingSenderId: '706382510190',
    projectId: 'flutternotify1',
    databaseURL: 'https://flutternotify1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutternotify1.appspot.com',
    iosBundleId: 'com.example.firebaselogin.RunnerTests',
  );
}
